apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://gitlab-service.gitlab.svc'
            - name: GITLAB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gitlab-secret
                  key: GITLAB_ROOT_PASSWORD
          volumeMounts:
            - name: gitlab-storage
              mountPath: /var/opt/gitlab
      volumes:
        - name: gitlab-storage
          persistentVolumeClaim:
            claimName: gitlab-pvc
